### ISSUE TITLE
Empty Password Should not be allowed

### ISSUE THREAD

**Issue by fhaque1** [jchua1/login#3]
Dear Jason Chua,

We cloned your repository today to search for some issues. One of the many issues is the fact that we were able to create an account with an empty password. This is very insecure. Please fix it when possible. Thank you.

From,
Shaeq Ahmed & Farhan Haque

**Comment by jchua1** [comment]
Dear Shaeq and Farhan,

Thanks for notifying me. It has been fixed.

From,
Jason Chua
